import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/create/Header";

export const metadata: Metadata = {
  title: "Velpam",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main>{children}</main>
    </>
  );
}
