import type { Metadata } from "next";
import "../globals.css";
import AdminHeader from "@/components/admin/AdminHeader";
import AdminSidebar from "@/components/admin/AdminSidebar";

export const metadata: Metadata = {
  title: "Velpam",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AdminHeader />
      <div className="flex w-full min-h-screen">
        <AdminSidebar />

        <main className="w-full">{children}</main>
      </div>
    </>
  );
}
