import type { Metadata } from "next";
import "../globals.css";
import ProviderHeader from "@/components/provider-components/ProviderHeader";

export const metadata: Metadata = {
  title: "Velpam",
  description: "Generated by create next app",
};

export default function ProviderLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ProviderHeader />
      <div className="w-full min-h-screen">
        <main className="w-full">{children}</main>
      </div>
    </>
  );
}
